### ISSUE TITLE
Please Add a LICENSE file to the repo

### ISSUE THREAD

**Issue by senrabc** [ctsit/redcapcustodian#119]
Please add an Apache 2 License file like the one here:  https://github.com/ctsit/qipr/blob/master/LICENSE. Please Edit line 189 to update year and add a reference to the AUTHORS file too.

**Comment by pbchase** [comment]
We should add a LICENSE or LICENSE.md (see https://r-pkgs.org/license.html#key-files)

As to AUTHORS file, we follow the R packaging standard for authors. It places a detailed, structured list of authors in the [DESCRIPTION](https://github.com/ctsit/redcapcustodian/blob/eaa9cf40e94b1d55a16953775cf9218327f3c301/DESCRIPTION#L5). Yet I think you are asking for something more. I'll make a PR with the LICENSE and assign @senrabc as reviewer

**Comment by pbchase** [comment]
I made a PR, but related to this, there is a role in the DESCRIPTION files Authors@R section for copyright holder. See https://r-pkgs.org/license.html#sec-how-to-include 

Who _should_ have the copyright on this? UF? The authors and UF?

Should I add an Authors@R for UF. I found a couple older discussions: https://github.com/r-lib/pkgdown/issues/1012,  https://stackoverflow.com/questions/50688357/description-authorsr-field-for-organizations

**Comment by pbchase** [comment]
@senrabc did you have any feed back on this or the PR (#124) I created?

**Comment by pbchase** [comment]
Addressed by PR #124
