### ISSUE TITLE
Pass DBI connection object to `write_summary_metrics`

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcapcustodian#120]
I feel like we should have passed the DBI connection object to `write_summary_metrics` instead of doing this:

https://github.com/ctsit/redcapcustodian/blob/43180b78d3c9eef85d947c55a9483a422b5aa2df/R/summary_metrics.R#L48

As I go to use `write_summary_metrics` in novel ways, testing is tricker because its harder to control the connection object it writes to. 

@ChemiKyle, what do you think?

**Comment by ChemiKyle** [comment]
#121 details the approach we discussed today

**Comment by ChemiKyle** [comment]
Closed by #122
