### ISSUE TITLE
Create functions to mirror dataframes into REDCap projects

### ISSUE THREAD

**Issue by ljwoodley** [ctsit/redcapcustodian#135]
We need to mirror dataframes into REDCap. 

## Spec for `mirror_data_to_redcap_project`

- [ ] The function `mirror_data_to_redcap_project` take a single parameter, `table_name`
- [ ] The function will read the environment to get the value of the environment variable named `<table_name>_pid`.
- [ ] The function will also read the value of the env variables named `CREDENTIALS_DB`.
- [ ] The function will search `CREDENTIALS_DB` for the REDCap API credentials for the current user in the PID pointed to by the value of `<table_name>_pid`.
- [ ] The function will use REDCapR::redcap_write() to write the data frame to the REDCap project described by those credentials.
- [ ] The function will return the complete results of `REDCapR::redcap_write()`

## Spec for `dataframe_to_redcap_dictionary`

If we can't find one in another R package, we should write a helper function named something like `dataframe_to_redcap_dictionary`. The function should output a CSV we can import into an empty REDCap project so that we could write the data of that dataframe into that project. The function should do these things:

- [ ] Transform the column names into a column of `field_name`
- [ ] Add a column, `form_name` with a value of `table_name`
- [ ] Add a column, `section_header` with a value of `as.character(NA)`
- [ ] Add a column `field_type` with a value of "text"
- [ ] Transform the column names into a column of `field_label`
- [ ] Add a column, `select_choices_or_calculations` with a value of `as.character(NA)`
- [ ] Add a column, `field_note` with a value of `as.character(NA)`
- [ ] Transform the column classes valid text validation types and write that to a column named 
text_validation_type_or_show_slider_number
- [ ] Return the constructed dataframe

If we do this, make this function part of REDCap Custodian.

For reference, see https://github.com/kamclean/collaborator/blob/master/R/data_dict.R which generates a different data dictionary despite being in a redcap-centric package. :-(

This issue was moved from https://github.com/ctsit/rcc.billing/issues/174

**Comment by ljwoodley** [comment]
1. Would `mirror_data_to_redcap_project` be an upsert or overwrite?

2. Should we account for all these validation types?

```
date_dmy, 
date_mdy,
date_ymd, 
datetime_dmy,
datetime_mdy,
datetime_ymd,
datetime_seconds_dmy,
datetime_seconds_mdy,
datetime_seconds_ymd,
email, 
integer,
alpha_only,
mrn_generic,
number, 
number_1dp,
number_2dp,
number_3dp, 
number_4dp,
phone, 
ssn, 
time_hh_mm_ss, 
time, time_mm_ss,
zipcode 
```

**Comment by pbchase** [comment]
> 1. Would `mirror_data_to_redcap_project` be an upsert, overwrite or append? Trying to determine how best to create the `record_id`.

You may assume that every mirrored table has a PK (aka record_id) and that every write event to that table you are mirroring into REDCap has that PK field in it.

**Comment by pbchase** [comment]
> 2\. Should we account for all these validation types?
> 
> ```
> date_dmy, 
> date_mdy,
> date_ymd, 
> datetime_dmy,
> datetime_mdy,
> datetime_ymd,
> datetime_seconds_dmy,
> datetime_seconds_mdy,
> datetime_seconds_ymd,
> email, 
> integer,
> alpha_only,
> mrn_generic,
> number, 
> number_1dp,
> number_2dp,
> number_3dp, 
> number_4dp,
> phone, 
> ssn, 
> time_hh_mm_ss, 
> time, time_mm_ss,
> zipcode 
> ```

Please support these validations:

- If you have a datetime column in the dataframe, set the validation type to `datetime_seconds_ymd`.
- If you have a date column in the dataframe, set the validation type to `datetime_ymd`.
- If the character data matches an email address pattern, set the validation type to `email`.
- If the class is numeric, set validation to `number`.

Everything else should probably be invalidated text. I say this, because REDCap is willing to do special things with columns if they are these types. The other column types are more to control data entry. I don't plan on any data entry for these forms, so there is no point in the additional complexity.
