### ISSUE TITLE
Port REDCapR wrapper functions from rcc.grace

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcapcustodian#147]
In the rcc.grace project, I made three functions that wrap REDCapR functions adding parameters that support REDCap custodian authentication methods. Copy those function into redcap custodian. Those functions are 

- [read_project_data.R](https://github.com/ctsit/rcc.grace/blob/main/R/read_project_data.R)
- [read_project_metadata.R](https://github.com/ctsit/rcc.grace/blob/main/R/read_project_metadata.R)
- [write_project_data.R](https://github.com/ctsit/rcc.grace/blob/main/R/write_project_data.R)

They have no test code, so you can just copy them to `./R/`, build the docs, and check the package.

**Comment by ChemiKyle** [comment]
Addressed by #148
