### ISSUE TITLE
logging is insufficient in `delete_project.R`

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcapcustodian#169]
The logging done by `delete_project.R` is to simplistic at 
https://github.com/ctsit/redcapcustodian/blob/0d088f9113b1e6c88bd6cbc588fe76615a5da60b/R/delete_project.R#L62

Because it is missing parameters, it doesn't show up in the REDCap event log UI. A proper deletion record looks like this:

```sql
INSERT INTO `redcap_log_event6` 
(`log_event_id`,  
 `project_id`, 
 `ts`, 
 `user`, 
 `ip`, 
 `page`, 
 `event`, 
 `object_type`, 
 `sql_log`, 
 `pk`, 
 `event_id`, 
 `data_values`, 
 `description`, 
 `legacy`, 
 `change_reason`)
VALUES
(34, 
 16, 
 20241118161942, 
 'admin', 
 '192.168.65.1', 
 'ProjectGeneral/delete_project.php', 
 'MANAGE', 
 'redcap_projects', 
 'update redcap_projects set date_deleted = \'2024-11-18 16:19:42\'\r\n					where project_id = 16 and date_deleted is null', 
 '16', 
 NULL, 
 'project_id = 16', 
 'Delete project', 
 0, 
 NULL)
```

At the moment, we log only `object_type, event, project_id, description`. We log them correctly, but we should also set
- `ts`: `format.Date(get_script_runtime(), format = '%Y%m%d%H%M%S')`
- `pk`: '<project_id>'
- `data_values`:  'project_id = <project_id>'
- `description`: 'Delete project'
- `legacy`: 0

Test how these appear in the REDCap UI. It's unclear how to set the other values, but we might have to set them to something. 

- We might reasonable set `page` to "rcc.billing::delete_abandoned_projects"
- Maybe set `sql_log` to the update statement generated at line 50 after refactoring that into an object.

**Comment by saipavan10-git** [comment]
Resolved by #171
