### ISSUE TITLE
Advertise on REDCap Tools

### ISSUE THREAD

**Issue by wibeasley** [ctsit/redcapcustodian#84]
@pbchase  & @ChemiKyle great presentation this morning at REDCapCon.  Consider listing your package on this page so more people might stumble in it (especially for those developers not on the community site).

https://redcap-tools.github.io/projects/

**Comment by wibeasley** [comment]
bump

**Comment by pbchase** [comment]
Created https://github.com/redcap-tools/redcap-tools.github.io/pull/58 which is now merged
